In [1]:
import pandas as pd
df=pd.read_csv("spam.csv", encoding="latin-1")

In [2]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [5]:
df=df.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis=1)

In [6]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df=df.rename(columns={'v1':'Target','v2':'Message'})

In [8]:
df

Target                                            Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le=LabelEncoder()

In [14]:
df['Target']=le.fit_transform(df['Target'])

In [15]:
df

Target                                            Message
0          0  Go until jurong point, crazy.. Available only ...
1          0                      Ok lar... Joking wif u oni...
2          1  Free entry in 2 a wkly comp to win FA Cup fina...
3          0  U dun say so early hor... U c already then say...
4          0  Nah I don't think he goes to usf, he lives aro...
...      ...                                                ...
5567       1  This is the 2nd time we have tried 2 contact u...
5568       0              Will Ì_ b going to esplanade fr home?
5569       0  Pity, * was in mood for that. So...any other s...
5570       0  The guy did some bitching but I acted like i'd...
5571       0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [19]:
df['Character']=df['Message'].apply(len)

In [20]:
df

Target                                            Message  Character
0          0  Go until jurong point, crazy.. Available only ...        111
1          0                      Ok lar... Joking wif u oni...         29
2          1  Free entry in 2 a wkly comp to win FA Cup fina...        155
3          0  U dun say so early hor... U c already then say...         49
4          0  Nah I don't think he goes to usf, he lives aro...         61
...      ...                                                ...        ...
5567       1  This is the 2nd time we have tried 2 contact u...        161
5568       0              Will Ì_ b going to esplanade fr home?         37
5569       0  Pity, * was in mood for that. So...any other s...         57
5570       0  The guy did some bitching but I acted like i'd...        125
5571       0                         Rofl. Its true to its name         26

[5572 rows x 3 columns]

In [22]:
df['Words']=df['Message'].apply(lambda x:len(x.split()))

In [23]:
df

Target                                            Message  Character  \
0          0  Go until jurong point, crazy.. Available only ...        111   
1          0                      Ok lar... Joking wif u oni...         29   
2          1  Free entry in 2 a wkly comp to win FA Cup fina...        155   
3          0  U dun say so early hor... U c already then say...         49   
4          0  Nah I don't think he goes to usf, he lives aro...         61   
...      ...                                                ...        ...   
5567       1  This is the 2nd time we have tried 2 contact u...        161   
5568       0              Will Ì_ b going to esplanade fr home?         37   
5569       0  Pity, * was in mood for that. So...any other s...         57   
5570       0  The guy did some bitching but I acted like i'd...        125   
5571       0                         Rofl. Its true to its name         26   

      Words  
0        20  
1         6  
2        28  
3        11  
4        13  
...     ...  
5567     30  
5568      8  
5569     10  
5570     26  
5571      6  

[5572 rows x 4 columns]

In [24]:
df.isna().sum()

Target       0
Message      0
Character    0
Words        0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(403)

In [27]:
df=df.drop_duplicates(keep='first')

In [28]:
df.duplicated().sum()

np.int64(0)

In [30]:
from nltk.tokenize import sent_tokenize

In [33]:
df.loc[:,'Sentences']=df['Message'].apply(lambda x: len(sent_tokenize(x)))

In [34]:
df

Target                                            Message  Character  \
0          0  Go until jurong point, crazy.. Available only ...        111   
1          0                      Ok lar... Joking wif u oni...         29   
2          1  Free entry in 2 a wkly comp to win FA Cup fina...        155   
3          0  U dun say so early hor... U c already then say...         49   
4          0  Nah I don't think he goes to usf, he lives aro...         61   
...      ...                                                ...        ...   
5567       1  This is the 2nd time we have tried 2 contact u...        161   
5568       0              Will Ì_ b going to esplanade fr home?         37   
5569       0  Pity, * was in mood for that. So...any other s...         57   
5570       0  The guy did some bitching but I acted like i'd...        125   
5571       0                         Rofl. Its true to its name         26   

      Words  Sentences  
0        20          2  
1         6          2  
2        28          2  
3        11          1  
4        13          1  
...     ...        ...  
5567     30          4  
5568      8          1  
5569     10          2  
5570     26          1  
5571      6          2  

[5169 rows x 5 columns]

In [35]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

In [37]:
def transformer (data):
    data = data.lower()
    data =re.sub(r'[^a-z0-9\s]', '', data)
    data=word_tokenize(data)

    stop_words = set(stopwords.words('english'))
    data=[word for word in data if word not in stop_words]
    stemming=PorterStemmer()
    data=[stemming.stem(word) for word in data]
    return ' '.join(data)

In [40]:
df.loc[:,'Clean']=df['Message'].apply(transformer)

In [41]:
df.sample(5)

Target                                            Message  Character  \
4452       0                         Or I guess  &lt;#&gt;  min         26   
4745       0         Orh i tot u say she now still dun believe.         42   
3610       0                   No. I.ll meet you in the library         32   
5351       0  Yup it's at paragon... I havent decided whethe...         67   
594        0  I met you as a stranger and choose you as my f...        147   

      Words  Sentences                                              Clean  
4452      5          1                                     guess ltgt min  
4745     10          1                     orh tot u say still dun believ  
3610      7          2                                   ill meet librari  
5351     12          2     yup paragon havent decid whether 2 cut yet hee  
594      28          4  met stranger choos friend long world stand fri...

In [42]:
df.head()

Target                                            Message  Character  \
0       0  Go until jurong point, crazy.. Available only ...        111   
1       0                      Ok lar... Joking wif u oni...         29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...        155   
3       0  U dun say so early hor... U c already then say...         49   
4       0  Nah I don't think he goes to usf, he lives aro...         61   

   Words  Sentences                                              Clean  
0     20          2  go jurong point crazi avail bugi n great world...  
1      6          2                              ok lar joke wif u oni  
2     28          2  free entri 2 wkli comp win fa cup final tkt 21...  
3     11          1                u dun say earli hor u c alreadi say  
4     13          1          nah dont think goe usf live around though

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [95]:
tfid=TfidfVectorizer(ngram_range=(1,2))

In [96]:
x=df['Clean']
y=df['Target']

In [97]:
x.shape

(5169,)

In [98]:
y.shape

(5169,)

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [101]:
x_train.shape

(4135,)

In [102]:
y_train.shape

(4135,)

In [103]:
x_test.shape

(1034,)

In [104]:
x_train_tfid = tfid.fit_transform(x_train)
x_test_tfid  = tfid.transform(x_test)


In [105]:
x_train_tfid

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 65908 stored elements and shape (4135, 32590)>

In [106]:
x_test_tfid

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10143 stored elements and shape (1034, 32590)>

In [107]:
from sklearn.naive_bayes import MultinomialNB

In [157]:
model = MultinomialNB(alpha=0.08)
model.fit(x_train_tfid, y_train)

MultinomialNB(alpha=0.08)

In [194]:
y_pred = model.predict(x_test_tfid)


In [195]:
y_pred


array([0, 0, 0, ..., 1, 0, 0], shape=(1034,))

In [ ]:
user_input = input("Enter a message: ")

clean_input = transformer(user_input)

input_tfidf = tfid.transform([clean_input])

prediction = model.predict(input_tfidf)


predictions=model.predict_proba(input_tfidf)[0][1]
if predictions>=0.5:
    print("🚨 Spam message")
else:
    print("✅ Not spam (Ham)")

In [189]:
model.classes_

array([0, 1])

In [193]:
model.predict_proba(input_tfidf)



array([[0.56346, 0.43654]])